#!/usr/bin/env bash
set -euo pipefail

mkdir -p 'CarStream'
cat > 'CarStream/.gitignore' <<'__CARSTREAM_2_0__'
.gradle/
.idea/
local.properties
**/build/
*.iml
.DS_Store
__CARSTREAM_2_0__

mkdir -p 'CarStream'
cat > 'CarStream/README.md' <<'__CARSTREAM_2_1__'
# CarStream MVP

CarStream turns an Android phone into a private in-car media server. The phone creates a Wi-Fi Direct group, serves a browser client to one or more tablets, and proxies download-ready TorBox video over the phone's cellular connection.

This branch is an MVP intended for testing on real Android hardware. Use it only with media you are authorized to access.

## Included features

- One Android app on the phone. Nothing is installed on the tablets.
- Wi-Fi Direct group creation from the phone app.
- Network name, password, and tablet URL shown in the phone UI.
- Multiple tablet clients at the same time.
- Independent video streams and playback state for each client.
- Live phone dashboard showing title, elapsed time, duration, play or pause state, and buffering state.
- Per-tablet play, pause, rewind 10 seconds, fast-forward 30 seconds, and choose-media controls.
- Parent can launch a selected movie or episode on a selected tablet.
- Three control modes:
  - Shared: child and parent may both control playback.
  - Parent locked: browser controls and library selection are disabled on the tablet.
  - Observe only: the phone displays state but its remote-control buttons are disabled.
- TorBox library browsing.
- Paste a magnet link on the phone to add it to TorBox.
- HTTP byte-range proxying so each tablet can seek without downloading from the beginning.
- TorBox API key encrypted with Android Keystore.
- TorBox API key and temporary download links never sent to the tablet.
- Foreground service, wake lock, and high-performance Wi-Fi lock while serving.

## Build

Open the `CarStream` directory in Android Studio and build the `app` module. The project targets Android API 35 and has a minimum Android version of 10, API 29.

The GitHub Actions workflow on the `carstream-mvp` branch runs unit tests and creates a debug APK artifact.

## First use

1. Install the debug APK on the phone.
2. Open CarStream and grant the nearby Wi-Fi permission. Android 12L and earlier request location permission because that is how those Android versions gate Wi-Fi Direct discovery and group management.
3. Enter and save the TorBox API key.
4. Tap **Start CarStream**.
5. On each tablet, join the Wi-Fi network displayed by the phone.
6. Open the displayed local address in Chrome.
7. Give each tablet a name.

## Important MVP limitations

- Direct browser playback is most reliable with MP4 files containing H.264 video and AAC audio. Chrome may not play MKV, some HEVC files, DTS audio, or other uncommon combinations. The server does not transcode in this version.
- A browser may require one physical tap before it allows a parent-initiated video to begin with sound. CarStream reports that condition to the phone and shows a large tap prompt on the tablet.
- Wi-Fi Direct behavior varies by phone manufacturer. The app first attempts a named nonpersistent group, then falls back to credentials generated by the phone.
- The MVP reads TorBox torrent items. Usenet and WebDL libraries are not yet included.
- Local phone files, subtitles, episode metadata, artwork, queues, and autoplay-next are not yet included.
- The phone uses a local HTTP server protected by a per-run access token and the Wi-Fi group's WPA passphrase. Traffic inside that private group is not separately encrypted with HTTPS.

## Architecture

```text
TorBox CDN
    |
    | cellular network selected per upstream connection
    v
Android phone
    |  TorBox API client and range proxy
    |  Wi-Fi Direct group owner
    |  HTTP server and WebSocket controller
    v
Tablet browsers
    |  independent HTML5 video players
    |  telemetry every second
    |  remote commands over WebSocket
```

Each tablet owns its player state. The phone's `ClientRegistry` maintains a separate WebSocket for each tablet and sends targeted commands. A video request occupies its own worker, so one client seeking or buffering does not alter another client's stream.
__CARSTREAM_2_1__

mkdir -p 'CarStream/app'
cat > 'CarStream/app/build.gradle' <<'__CARSTREAM_2_2__'
plugins {
    id 'com.android.application'
}

android {
    namespace 'com.carstream.app'
    compileSdk 35

    defaultConfig {
        applicationId 'com.carstream.app'
        minSdk 29
        targetSdk 35
        versionCode 1
        versionName '0.1.0-mvp'

        testInstrumentationRunner 'android.test.InstrumentationTestRunner'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
}
__CARSTREAM_2_2__

mkdir -p 'CarStream/app'
cat > 'CarStream/app/proguard-rules.pro' <<'__CARSTREAM_2_3__'
# No shrinking in the MVP build.
__CARSTREAM_2_3__

mkdir -p 'CarStream/app/src/main'
cat > 'CarStream/app/src/main/AndroidManifest.xml' <<'__CARSTREAM_2_4__'
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android">

    <uses-feature
        android:name="android.hardware.wifi.direct"
        android:required="false" />

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.CHANGE_WIFI_STATE" />
    <uses-permission android:name="android.permission.CHANGE_NETWORK_STATE" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE_CONNECTED_DEVICE" />
    <uses-permission
        android:name="android.permission.ACCESS_FINE_LOCATION"
        android:maxSdkVersion="32" />
    <uses-permission
        android:name="android.permission.NEARBY_WIFI_DEVICES"
        android:usesPermissionFlags="neverForLocation" />

    <application
        android:allowBackup="true"
        android:label="@string/app_name"
        android:supportsRtl="true"
        android:theme="@android:style/Theme.Material.Light.NoActionBar"
        android:usesCleartextTraffic="true">

        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:screenOrientation="portrait">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

        <service
            android:name=".CarStreamService"
            android:exported="false"
            android:foregroundServiceType="connectedDevice" />

    </application>
</manifest>
__CARSTREAM_2_4__

mkdir -p 'CarStream/app/src/main/assets'
cat > 'CarStream/app/src/main/assets/app.js' <<'__CARSTREAM_2_5__'
(() => {
  "use strict";

  const qs = new URLSearchParams(location.search);
  const suppliedToken = qs.get("token");
  if (suppliedToken) localStorage.setItem("carstreamToken", suppliedToken);
  const token = suppliedToken || localStorage.getItem("carstreamToken") || "";
  const generatedId = (crypto.randomUUID ? crypto.randomUUID() :
    `tablet-${Date.now()}-${Math.random().toString(16).slice(2)}`);
  const clientId = localStorage.getItem("carstreamClientId") || generatedId;
  localStorage.setItem("carstreamClientId", clientId);

  const el = id => document.getElementById(id);
  const video = el("video");
  const onboarding = el("onboarding");
  const playerPanel = el("playerPanel");
  const libraryPanel = el("libraryPanel");
  const lockedBanner = el("lockedBanner");
  const gestureButton = el("gestureButton");
  let clientName = localStorage.getItem("carstreamClientName") || "";
  let socket = null;
  let reconnectTimer = null;
  let currentMedia = null;
  let library = [];
  let controlMode = "SHARED";
  let buffering = false;
  let needsGesture = false;

  function initialize() {
    if (!token) {
      onboarding.classList.remove("hidden");
      el("nameInput").value = clientName;
      el("startButton").disabled = true;
      el("startButton").textContent = "Open the address shown on the phone";
      return;
    }
    el("clientName").textContent = clientName ? `• ${clientName}` : "";
    if (clientName) {
      showApp();
      connectSocket();
      loadLibrary();
    } else {
      onboarding.classList.remove("hidden");
      el("nameInput").focus();
    }
  }

  function showApp() {
    onboarding.classList.add("hidden");
    playerPanel.classList.remove("hidden");
    libraryPanel.classList.remove("hidden");
    el("clientName").textContent = `• ${clientName}`;
  }

  el("startButton").addEventListener("click", async () => {
    const value = el("nameInput").value.trim();
    if (!value) return;
    clientName = value;
    localStorage.setItem("carstreamClientName", clientName);
    showApp();
    connectSocket();
    loadLibrary();
    try {
      video.muted = true;
      await video.play();
      video.pause();
      video.muted = false;
    } catch (_) { }
  });

  el("renameButton").addEventListener("click", () => {
    const next = prompt("Tablet name", clientName);
    if (!next || !next.trim()) return;
    clientName = next.trim();
    localStorage.setItem("carstreamClientName", clientName);
    el("clientName").textContent = `• ${clientName}`;
    send({ type: "rename", name: clientName });
  });

  el("search").addEventListener("input", renderLibrary);
  el("playButton").addEventListener("click", () => video.paused ? attemptPlay() : video.pause());
  document.querySelector('[data-command="back"]').addEventListener("click", () => seekRelative(-10));
  document.querySelector('[data-command="forward"]').addEventListener("click", () => seekRelative(30));
  el("fullscreenButton").addEventListener("click", () => {
    const target = video.parentElement;
    if (target.requestFullscreen) target.requestFullscreen();
  });
  gestureButton.addEventListener("click", attemptPlay);

  function connectSocket() {
    clearTimeout(reconnectTimer);
    if (socket && (socket.readyState === WebSocket.OPEN || socket.readyState === WebSocket.CONNECTING)) return;
    const scheme = location.protocol === "https:" ? "wss" : "ws";
    socket = new WebSocket(`${scheme}://${location.host}/ws?token=${encodeURIComponent(token)}`);
    socket.addEventListener("open", () => {
      setConnection(true);
      send({ type: "hello", clientId, name: clientName, userAgent: navigator.userAgent });
      sendTelemetry();
    });
    socket.addEventListener("message", event => {
      try { handleMessage(JSON.parse(event.data)); } catch (_) { }
    });
    socket.addEventListener("close", () => {
      setConnection(false);
      reconnectTimer = setTimeout(connectSocket, 1500);
    });
    socket.addEventListener("error", () => socket.close());
  }

  function setConnection(online) {
    el("connection").textContent = online ? "online" : "offline";
    el("connection").className = `status ${online ? "online" : "offline"}`;
  }

  function send(message) {
    if (socket && socket.readyState === WebSocket.OPEN) socket.send(JSON.stringify(message));
  }

  async function loadLibrary() {
    el("libraryMessage").textContent = "Loading library...";
    try {
      const response = await fetch(`/api/library?token=${encodeURIComponent(token)}`, { cache: "no-store" });
      if (!response.ok) throw new Error(`HTTP ${response.status}`);
      const result = await response.json();
      library = result.items || [];
      el("libraryMessage").textContent = library.length ? "" :
        (result.configured ? "No playable, download-ready videos were found." : "TorBox is not configured on the phone.");
      renderLibrary();
    } catch (error) {
      el("libraryMessage").textContent = `Could not load library: ${error.message}`;
    }
  }

  function renderLibrary() {
    const container = el("library");
    container.replaceChildren();
    const needle = el("search").value.trim().toLowerCase();
    const items = library.filter(item => !needle || item.title.toLowerCase().includes(needle)
      || (item.path || "").toLowerCase().includes(needle));
    for (const item of items) {
      const button = document.createElement("button");
      button.className = "media-card";
      button.disabled = controlMode === "PARENT_LOCKED" || !item.ready;
      const title = document.createElement("strong");
      title.className = "media-title";
      title.textContent = item.title;
      const meta = document.createElement("span");
      meta.className = "media-meta";
      meta.textContent = item.ready ? formatBytes(item.size) : "Preparing in TorBox";
      button.append(title, meta);
      button.addEventListener("click", () => setMedia(item, 0, true));
      container.appendChild(button);
    }
  }

  function handleMessage(message) {
    if (message.type === "welcome") {
      applyControlMode(message.controlMode || "SHARED");
      return;
    }
    if (message.type !== "command") return;
    switch (message.action) {
      case "play": attemptPlay(); break;
      case "pause": video.pause(); break;
      case "seekRelative": seekRelative(Number(message.seconds) || 0); break;
      case "seekTo": video.currentTime = clamp(Number(message.seconds) || 0, 0, video.duration || Infinity); break;
      case "setMedia": setMedia(message.media, Number(message.startAt) || 0, message.autoplay !== false); break;
      case "controlMode": applyControlMode(message.mode || "SHARED"); break;
    }
  }

  function setMedia(item, startAt, autoplay) {
    currentMedia = item;
    needsGesture = false;
    gestureButton.classList.add("hidden");
    el("nowTitle").textContent = item.title || "Untitled video";
    video.src = `/stream/${encodeURIComponent(item.id)}?token=${encodeURIComponent(token)}`;
    video.load();
    const seekWhenReady = () => {
      if (startAt > 0 && Number.isFinite(video.duration)) video.currentTime = Math.min(startAt, video.duration);
      if (autoplay) attemptPlay();
      video.removeEventListener("loadedmetadata", seekWhenReady);
    };
    video.addEventListener("loadedmetadata", seekWhenReady);
    sendTelemetry();
  }

  async function attemptPlay() {
    try {
      await video.play();
      needsGesture = false;
      gestureButton.classList.add("hidden");
    } catch (_) {
      needsGesture = true;
      gestureButton.classList.remove("hidden");
      sendTelemetry();
    }
  }

  function seekRelative(seconds) {
    if (!Number.isFinite(video.currentTime)) return;
    video.currentTime = clamp(video.currentTime + seconds, 0, video.duration || Infinity);
  }

  function applyControlMode(mode) {
    controlMode = mode;
    const locked = mode === "PARENT_LOCKED";
    lockedBanner.classList.toggle("hidden", !locked);
    el("customControls").classList.toggle("hidden", locked);
    el("search").disabled = locked;
    video.controls = !locked;
    renderLibrary();
    sendTelemetry();
  }

  function sendTelemetry() {
    send({
      type: "telemetry",
      mediaId: currentMedia ? currentMedia.id : "",
      title: currentMedia ? currentMedia.title : "Nothing playing",
      position: Number.isFinite(video.currentTime) ? video.currentTime : 0,
      duration: Number.isFinite(video.duration) ? video.duration : 0,
      paused: video.paused,
      buffering,
      needsGesture,
      controlMode
    });
    updatePlayerText();
  }

  function updatePlayerText() {
    el("playButton").textContent = video.paused ? "Play" : "Pause";
    el("timeText").textContent = `${formatTime(video.currentTime)} / ${formatTime(video.duration)}`;
  }

  video.addEventListener("waiting", () => { buffering = true; sendTelemetry(); });
  video.addEventListener("playing", () => { buffering = false; needsGesture = false; gestureButton.classList.add("hidden"); sendTelemetry(); });
  video.addEventListener("pause", sendTelemetry);
  video.addEventListener("ended", sendTelemetry);
  video.addEventListener("timeupdate", updatePlayerText);
  setInterval(sendTelemetry, 1000);
  setInterval(loadLibrary, 30000);

  function formatTime(value) {
    if (!Number.isFinite(value) || value < 0) value = 0;
    const total = Math.floor(value);
    const h = Math.floor(total / 3600);
    const m = Math.floor((total % 3600) / 60);
    const s = total % 60;
    return h ? `${h}:${String(m).padStart(2, "0")}:${String(s).padStart(2, "0")}` : `${m}:${String(s).padStart(2, "0")}`;
  }

  function formatBytes(value) {
    const n = Number(value) || 0;
    if (!n) return "Video";
    if (n >= 1073741824) return `${(n / 1073741824).toFixed(1)} GB`;
    return `${Math.round(n / 1048576)} MB`;
  }

  function clamp(value, min, max) { return Math.max(min, Math.min(max, value)); }

  initialize();
})();
__CARSTREAM_2_5__
